# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f5b3abf237bdb08ebf570db8d4547d495166a11fd32e3d5e62962cb26b9330c63f70cf337898230b490b484a8503de9ed22793d880bf124343d2e9a1ca0cf27

test:
  secret_key_base: 926a07e06ff72cf48e95da35ed6df5453f960e0c3047cbd50d5a78380b1b72a96605c899af9ed4bb743d0b61566f93e5ece12e04765365c01754b07890a47c19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
